---
# Install OMERO.server and OMERO.web with a public user on localhost

# - hosts: all
- hosts: omero-addons

  pre_tasks:

    - name: Ensure openssl is installed
      become: true
      package:
        name: openssl
        state: present

  roles:

    - role: ome.postgresql
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases:
            - omero

    - role: ome.omero_server
      omero_server_release: latest
      omero_server_python_addons:
        # Needed for OMERO.figure export
        - markdown
        - reportlab
      omero_server_config_set:
        # Enable web-sockets
        omero.client.icetransports: ssl,tcp,wss
      ## Uncomment to scale up for more users.
      # Disabling permits testing on smaller VMs.
      #   omero.db.poolsize: 50
      #   omero.jvmcfg.percent.blitz: 50
      #   omero.jvmcfg.percent.indexer: 20
      #   omero.jvmcfg.percent.pixeldata: 20

      # These two are optional on Centos, required on Ubuntu
      # For more information on why omero_server_selfsigned_certificates
      # is required see
      # https://forum.image.sc/t/omero-icessl-unable-to-set-ciphers/30704
      omero_server_systemd_require_network: false
      omero_server_selfsigned_certificates: true

    - role: ome.omero_web
      omero_web_config_set:
        omero.web.public.enabled: true
        omero.web.public.server_id: 1
        omero.web.public.user: public
        omero.web.public.password: "{{ omero_web_public_password }}"
        omero.web.public.url_filter: "^/(webadmin/myphoto/|webclient/\
          (?!(action|logout|annotate_(file|tags|comment|rating|map)|\
          script_ui|ome_tiff|figure_script))|\
          webgateway/(?!(archived_files|download_as))\
          |iviewer/|mapr/|figure/)"
        omero.web.nginx_server_extra_config:
          # Proxy websockets through Nginx alongside OMERO.web
          - location ~ ^/omero-ws(/.*)?$ {
          - proxy_pass https://localhost:4066;
          - proxy_http_version 1.1;
          - proxy_set_header Upgrade $http_upgrade;
          - proxy_set_header Connection "Upgrade";
          - proxy_read_timeout 86400;
          - "}"
          # Proxy omero-ms-zarr
          - location ~^/image/ {
          - proxy_pass http://localhost:8080;
          - "}"
        # Uncomment to configure SSL certificates
        #   - "listen 443 ssl;"
        #   - "ssl_certificate {{ ssl_certificate_public_path }};"
        #   - "ssl_certificate_key {{ ssl_certificate_key_path }};"
      omero_web_apps_packages:
        - omero-figure
        - omero-iviewer
        - omero-mapr
        - omero-parade
      omero_web_apps_names:
        - omero_figure
        - omero_iviewer
        - omero_mapr
        - omero_parade
      omero_web_apps_config_set:
        omero.web.viewer.view: omero_iviewer.views.index
        omero.web.mapr.config:
          - menu: anyvalue
            config:
              default:
                - Any Value
              all: []
              ns:
                - openmicroscopy.org/omero/client/mapAnnotation
              label: Any
      omero_web_apps_config_append:
        omero.web.open_with:
          - - omero_iviewer
            - omero_iviewer_index
            - supported_objects:
                - images
                - dataset
                - well
              script_url: omero_iviewer/openwith.js
              label: OMERO.iviewer
          - - omero_figure
            - new_figure
            - supported_objects:
                - images
              target: _blank
              label: OMERO.figure
        omero.web.ui.center_plugins:
          - - Parade
            - omero_parade/init.js.html
            - omero_parade
      omero_web_apps_top_links:
        - label: Figure
          link: figure_index
          attrs:
            title: Open Figure in new tab
            target: _blank
        - label: Any Value
          link:
            viewname: maprindex_anyvalue
          attrs:
            title: Find Any Value

    - role: ome.omero_user
      omero_user_bin_omero: /opt/omero/server/OMERO.server/bin/omero
      omero_user_system: omero-server
      omero_user_admin_user: root
      omero_user_admin_pass: "{{ omero_server_rootpassword }}"
      omero_group_create:
        - name: public
          type: read-only
      omero_user_create:
        - login: public
          firstname: public
          lastname: user
          password: "{{ omero_web_public_password }}"
          groups: "--group-name public"

  tasks:

    - name: selinux nginx allow omero wss
      become: true
      seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true
      when: selinux_enabled

    - name: Copy Figure_To_Pdf.py script
      become: true
      become_user: omero-server
      copy:
        dest:
          /opt/omero/server/OMERO.server/lib/scripts/omero/figure_scripts/Figure_To_Pdf.py
        remote_src: true
        src:
          /opt/omero/web/venv3/lib/python3.6/site-packages/omero_figure/scripts/omero/figure_scripts/Figure_To_Pdf.py

  vars:
    postgresql_version: "11"
    omero_server_rootpassword: ChangeMe
    omero_web_public_password: public


- hosts: omero-addons

  roles:

    - role: ome.deploy_archive
      become: true
      deploy_archive_dest_dir: /opt/omero/omero-ms-zarr
      deploy_archive_src_url: >
        https://users.openmicroscopy.org.uk/~spli/testing/omero-ms-zarr-shadow-0.1.1-SNAPSHOT-v0.1.2.zip
      deploy_archive_sha256: >
        c0c4121b50e765055ce3f1da51647ee40a21a68b33e923ce9048aa21c42052af
      deploy_archive_symlink: /opt/omero/omero-ms-zarr/omero-ms-zarr
      deploy_archive_internal_root: omero-ms-zarr-shadow-0.1.1-SNAPSHOT
      # TODO: restart omero-ms-zarr if it's already installed
      # deploy_archive_notifies:

  tasks:

    - name: Create omero-ms-zarr configuration
      become: true
      template:
        src: omero-ms-zarr.properties.j2
        dest: /opt/omero/omero-ms-zarr/omero-ms-zarr.properties

    - name: Create omero-ms-zarr systemd service
      become: true
      template:
        src: omero-ms-zarr.service.j2
        dest: /etc/systemd/system/omero-ms-zarr.service

    - name: Enable and start omero-ms-zarr systemd service
      become: true
      service:
        enabled: true
        name: omero-ms-zarr.service
        state: started
