---

- src: ome.deploy_archive
  version: 0.1.3

- src: ome.postgresql
  version: 5.0.1

- src: ome.omero_server
  version: 3.3.0

- src: ome.omero_web
  version: 3.1.0

- src: ome.omero_user
  version: 0.2.0
