---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
platforms:
  - name: omero-addons
    image: jrei/systemd-ubuntu:20.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
scenario:
  name: ubuntu2004
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
